---
title: "Client Report - Project 1"
subtitle: "Course DS 250"
author: "Keith Crawford"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## History of Name Usage

_Traditional English names have taken a nosedive since the change of the century. All the names I researched peaked from 1950-1990, and they all took nosedives by 2000 in terms of usage. The newer generations are turning away from tradition and trying to be more creative, rather than picking names from scripture, or pop culture, or trends. Out with the old and in with the new._


```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```



## My name's historic usage

__How does your name at your birth year compare to its use historically?__

_Looks like my name peaked in the 1950's to 1960's, and it's been on a steady decline since. The arrow shows there was only about 1600 Keiths born in 1999, a far cry from the 12,000 Keiths around it's peak._

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here


```


```{python}
#| label: Q1 chart
#| code-summary: plot example
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
# Creating a filter to see my names usage in my birth year
filter= df[(df.name == "Keith") & (df.year == 1999)]
# Keith's historic usage filter
kdf= df[df.name== "Keith"]

chart = px.line(
    kdf,
    x="year",
    y="Total",
    title= "Keith's Historic Usage"
)
chart.add_annotation(
    x=1999,
    y=1642,
    text= "Keiths born in 1999",
    showarrow= True,
    arrowhead= 2,
    arrowsize=1,
    arrowwidth=2
)

chart.show()


```


```{python}
#| label: Q1 table
#| code-summary: table example
#| tbl-cap: ""
#| tbl-cap-location: top
# Include and execute your code here

```


## Guessing Brittany's age

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_Just off my own intuition I would say somewhere between 30-50. I don't know too many near my age, nor many younger. This is backed up by the line chart since it peaked in the 90s and has been on a drastic decline since._

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here


```



```{python}
#| label: Q2 chart
#| code-summary: plot example
#| fig-cap: "Brittany's Historic Usage"
#| fig-align: center
# Include and execute your code here
filter = df[df.name=="Brittany"]
chart = px.line(
    filter,
    x="year", 
    y="Total",
    title="Brittany's Historic Usage"
)
chart.add_annotation(
    text="Brittany's Peak",
    x=1990,
    y=32000,
    showarrow= True,
    arrowsize=1,
    arrowhead=2,
    arrowwidth=2
)
chart.show()

```


```{python}
#| label: Q2 table
#| code-summary: table example
#| tbl-cap: ""
#| tbl-cap-location: top
# Include and execute your code here


```


## Christian name usage over time

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_Mary was already far more popular going into 1920, had a short dip and then along with the other 3 peaked during the 1950's (Mary had 53,000 babies named after her in 1950!), before all 4 names took a nosedive in the 60's and beyond. By 2000 they were all under 10,000 in terms of babies being named after them._

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here


```



```{python}
#| label: Q3 chart
#| code-summary: plot example
#| fig-cap: "Christian Name Comparison"
#| fig-align: center
# Include and execute your code here
mmppfilter= df[(df.year > 1919) & (df.year < 2001) & (df.name=="Mary") | (df.name=="Martha") | (df.name=="Paul") | (df.name=="Peter")]
chart = px.line(
    mmppfilter,
    x="year", 
    y="Total",
    title= "Change in Popular Christian Name Usage 1920-2000", 
    color= "name"
)
chart.add_annotation(
    text="1920 starts here",
    x=1920,
    y=20000,
    showarrow=True,
    arrowsize=1,
    arrowhead=2,
    arrowwidth=2
)

chart.show()
```


```{python}
#| label: Q3 table
#| code-summary: table example
#| tbl-cap: ""
#| tbl-cap-location: top
# Include and execute your code here


```

## Movies effect on names

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_So turns out Rocky actually peaked in the 50's/early 60's it looks like. Still, it had dipped below 200 a year before the movie "Rocky" came out, where it had a temporary resurgence until the early 90's._

```{python}
#| label: Q4
#| code-summary: Read and format data
# Include and execute your code here


```



```{python}
#| label: Q4 chart
#| code-summary: plot example
#| fig-cap: "Rocky after 1976"
#| fig-align: center
# Include and execute your code here
#Filtering for Rocky, a name that became famous after the movie "Rocky" starring Sylvester Stallone
filter= df[df.name== "Rocky"]

chart = px.line(
    filter,
    x="year", 
    y="Total",
)
chart.add_annotation(
    text= "Rocky comes out",
    x=1976,
    y=373, 
    showarrow=True,
    arrowsize=1,
    arrowhead=2,
    arrowwidth=2
)
chart.show()
```


```{python}
#| label: Q4 table
#| code-summary: table example
#| tbl-cap: ""
#| tbl-cap-location: top
# Include and execute your code here


```